import pyautogui as py

for i in range(631):
    print(i)
    py.moveTo(240, 230)
    py.click()
    py.sleep(0.5)
    py.keyDown('f2')
    py.sleep(0.5)
    py.hotkey('ctrl', 'c')
    py.sleep(0.5)
    py.keyDown('esc')
    py.sleep(0.7)
    py.doubleClick()
    py.sleep(0.7)
    py.click()
    py.sleep(0.7)
    py.keyDown('down')
    #py.doubleClick()
    py.sleep(0.7)
    #py.click()
    py.keyDown('enter')
    py.sleep(1)
    py.click()
    py.sleep(1)
    py.keyDown('f2')
    py.sleep(0.7)
    py.hotkey('ctrl', 'v')
    py.sleep(0.7)
    py.keyDown('enter')
    py.sleep(0.7)
    py.hotkey('ctrl', 'c')
    py.sleep(0.5)
    py.moveTo(1020, 230)
    py.sleep(0.5)
    py.click()
    py.sleep(0.5)
    py.hotkey('ctrl', 'v')
    py.sleep(0.5)
    py.moveTo(240, 230)
    py.sleep(0.5)
    py.click()
    py.sleep(0.5)
    py.keyDown('backspace')
    py.sleep(1.5)
    py.keyDown('backspace')
    py.sleep(1.5)
    py.keyDown('delete')
    #py.keyDown('enter')
    py.sleep(1)
